#!/usr/bin/env php
<?php

declare(strict_types=1);

#region USE

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

#endregion

define('LARAVEL_START', microtime(true));

// Register the composer autoloader.
require __DIR__ . '/vendor/autoload.php';

/**
 * Bootstrap Laravel and handle the command.
 *
 * @var Application $app
 */
$app = require_once __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
